from pathlib import Path
from datetime import datetime
import shutil
import json

ROOT = Path.cwd()
BACKUP_ROOT = ROOT / "backup_before_webcut_part1"
STAMP = datetime.now().strftime("%Y%m%d_%H%M%S")
BACKUP_DIR = BACKUP_ROOT / STAMP

FILES = {}

FILES["package.json"] = [
    "{",
    "  \"name\": \"webcut-ai-creativeops-agent-platform\",",
    "  \"version\": \"0.1.0\",",
    "  \"private\": true,",
    "  \"scripts\": {",
    "    \"dev\": \"next dev\",",
    "    \"build\": \"next build\",",
    "    \"start\": \"next start\"",
    "  },",
    "  \"dependencies\": {",
    "    \"@next/env\": \"latest\",",
    "    \"next\": \"latest\",",
    "    \"react\": \"latest\",",
    "    \"react-dom\": \"latest\"",
    "  }",
    "}",
]

FILES[".gitignore"] = [
    "node_modules/",
    ".next/",
    "out/",
    "dist/",
    ".env",
    ".env.local",
    ".env.development.local",
    ".env.test.local",
    ".env.production.local",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    "pnpm-debug.log*",
    ".DS_Store",
    "Thumbs.db",
    "backup_before_webcut_part1/",
]

FILES[".env.example"] = [
    "NEXT_PUBLIC_SITE_URL=https://webcut.ai",
    "WEBCUT_ENV=local",
    "AZURE_OPENAI_ENDPOINT=",
    "AZURE_OPENAI_API_KEY=",
    "AZURE_OPENAI_DEPLOYMENT=",
    "AZURE_AI_FOUNDRY_PROJECT_ENDPOINT=",
    "AZURE_AI_FOUNDRY_AGENT_ID=",
    "AWS_REGION=us-east-1",
    "AWS_BEDROCK_MODEL_ID=",
    "S3_INPUT_BUCKET=",
    "S3_OUTPUT_BUCKET=",
]

FILES["jsconfig.json"] = [
    "{",
    "  \"compilerOptions\": {",
    "    \"baseUrl\": \".\",",
    "    \"paths\": {",
    "      \"@/*\": [\"./*\"]",
    "    }",
    "  }",
    "}",
]

FILES["next.config.mjs"] = [
    "const nextConfig = {",
    "  reactStrictMode: true,",
    "};",
    "",
    "export default nextConfig;",
]

FILES["README.md"] = [
    "# WebCut.ai CreativeOps Agent Platform",
    "",
    "WebCut.ai is an AI creative operations, media intelligence and automation platform for modern content teams.",
    "It combines design workspace foundations, AI media enhancement, human approval, governance and future agent orchestration in one production style full stack project.",
    "",
    "## Part 1 status",
    "",
    "This repository now contains the first working development foundation:",
    "",
    "| Area | Included in Part 1 |",
    "| --- | --- |",
    "| Web app | Next.js App Router landing page and product modules |",
    "| Studio shell | Browser studio placeholder for future editor workflows |",
    "| AI Lab | Placeholder for text to speech, speech to text, enhancement and generation workflows |",
    "| API Lab | Health check and creative brief endpoint |",
    "| MCP surface | Placeholder for future Model Context Protocol tools |",
    "| Governance | Human approval and audit trail concepts in UI copy |",
    "",
    "## Local setup",
    "",
    "Run these commands from the repository root:",
    "",
    "```cmd",
    "npm install",
    "npm run dev",
    "```",
    "",
    "Open:",
    "",
    "```text",
    "http://localhost:3000",
    "```",
    "",
    "Health check:",
    "",
    "```cmd",
    "curl http://localhost:3000/api/health",
    "```",
    "",
    "Creative brief test:",
    "",
    "```cmd",
    "curl -X POST http://localhost:3000/api/ai/creative-brief -H \"Content-Type: application/json\" -d \"{\\\"brand\\\":\\\"WebCut.ai\\\",\\\"goal\\\":\\\"Create an AI media enhancement campaign\\\",\\\"audience\\\":\\\"content creators\\\"}\"",
    "```",
    "",
    "## Development roadmap",
    "",
    "1. Part 1: Foundation, routes, design system and mock API endpoints.",
    "2. Part 2: Real creative workspace with canvas, uploads and asset library.",
    "3. Part 3: AI media intelligence API layer for text to speech, speech to text, video denoising, sharpening, 4K enhancement and image enhancement.",
    "4. Part 4: Agent orchestration with adapters for LangChain, LangGraph, Model Context Protocol, LlamaIndex, CrewAI, AutoGen, Semantic Kernel, DSPy, LiteLLM, Ollama and vLLM.",
    "5. Part 5: AWS native production architecture with storage, queues, approvals, observability, governance and deployment workflows.",
]

FILES["app/layout.js"] = [
    "import \"./globals.css\";",
    "",
    "export const metadata = {",
    "  title: \"WebCut.ai CreativeOps Agent Platform\",",
    "  description: \"AI creative operations, media intelligence and automation platform.\",",
    "};",
    "",
    "export default function RootLayout({ children }) {",
    "  return (",
    "    <html lang=\"en\">",
    "      <body>{children}</body>",
    "    </html>",
    "  );",
    "}",
]

FILES["app/page.js"] = [
    "import Link from \"next/link\";",
    "import { platformModules, launchSteps, agentStack } from \"@/lib/platformData\";",
    "",
    "export default function HomePage() {",
    "  return (",
    "    <main className=\"page-shell\">",
    "      <section className=\"hero-grid\">",
    "        <div className=\"hero-copy\">",
    "          <p className=\"eyebrow\">Nebula Flux Interface · Part 1 Foundation</p>",
    "          <h1>WebCut.ai CreativeOps Agent Platform</h1>",
    "          <p className=\"hero-text\">",
    "            A futuristic AI creative operations and media intelligence platform for design workflows, media enhancement, human approvals and agentic automation.",
    "          </p>",
    "          <div className=\"button-row\">",
    "            <Link href=\"/studio\" className=\"primary-button\">Open Studio</Link>",
    "            <Link href=\"/api-lab\" className=\"secondary-button\">Test API Lab</Link>",
    "          </div>",
    "        </div>",
    "        <div className=\"hero-panel\">",
    "          <div className=\"orb orb-one\" />",
    "          <div className=\"orb orb-two\" />",
    "          <div className=\"glass-card\">",
    "            <span>Live Architecture</span>",
    "            <strong>Creative agents · media tools · governance</strong>",
    "            <p>Prepared for AWS native workloads, Azure AI placeholders and Model Context Protocol style tool surfaces.</p>",
    "          </div>",
    "        </div>",
    "      </section>",
    "",
    "      <section className=\"section\">",
    "        <div className=\"section-heading\">",
    "          <p className=\"eyebrow\">Core Platform Modules</p>",
    "          <h2>One operating layer for AI powered creative work</h2>",
    "        </div>",
    "        <div className=\"card-grid\">",
    "          {platformModules.map((module) => (",
    "            <article className=\"feature-card\" key={module.title}>",
    "              <span className=\"card-icon\">{module.icon}</span>",
    "              <h3>{module.title}</h3>",
    "              <p>{module.description}</p>",
    "            </article>",
    "          ))}",
    "        </div>",
    "      </section>",
    "",
    "      <section className=\"split-section\">",
    "        <div>",
    "          <p className=\"eyebrow\">Agent Stack</p>",
    "          <h2>Built for multi agent creative automation</h2>",
    "          <p className=\"muted\">Part 1 adds a clean surface. Later parts will connect real model calls, asset pipelines, approval workflows and observability.</p>",
    "        </div>",
    "        <div className=\"stack-list\">",
    "          {agentStack.map((item) => (",
    "            <div className=\"stack-item\" key={item.name}>",
    "              <strong>{item.name}</strong>",
    "              <span>{item.role}</span>",
    "            </div>",
    "          ))}",
    "        </div>",
    "      </section>",
    "",
    "      <section className=\"section\">",
    "        <div className=\"section-heading\">",
    "          <p className=\"eyebrow\">Build Sequence</p>",
    "          <h2>Development path from foundation to production architecture</h2>",
    "        </div>",
    "        <div className=\"timeline\">",
    "          {launchSteps.map((step) => (",
    "            <div className=\"timeline-item\" key={step.phase}>",
    "              <span>{step.phase}</span>",
    "              <div>",
    "                <h3>{step.title}</h3>",
    "                <p>{step.detail}</p>",
    "              </div>",
    "            </div>",
    "          ))}",
    "        </div>",
    "      </section>",
    "    </main>",
    "  );",
    "}",
]

FILES["app/studio/page.js"] = [
    "import Link from \"next/link\";",
    "",
    "export default function StudioPage() {",
    "  return (",
    "    <main className=\"page-shell compact\">",
    "      <Link href=\"/\" className=\"back-link\">← Back to home</Link>",
    "      <section className=\"workspace\">",
    "        <div className=\"workspace-sidebar\">",
    "          <p className=\"eyebrow\">Browser Studio</p>",
    "          <h1>Creative workspace shell</h1>",
    "          <p className=\"muted\">This is the first UI shell for future canvas editing, templates, brand kits, uploads and generated media layers.</p>",
    "          <button className=\"primary-button button-reset\">Generate concept</button>",
    "        </div>",
    "        <div className=\"canvas-shell\">",
    "          <div className=\"canvas-frame\">",
    "            <span>1080 × 1080</span>",
    "            <h2>AI campaign visual</h2>",
    "            <p>Drop assets, prompts and brand rules here in Part 2.</p>",
    "          </div>",
    "        </div>",
    "      </section>",
    "    </main>",
    "  );",
    "}",
]

FILES["app/dashboard/page.js"] = [
    "import Link from \"next/link\";",
    "",
    "const metrics = [",
    "  { label: \"Creative jobs\", value: \"128\" },",
    "  { label: \"Human approvals\", value: \"14\" },",
    "  { label: \"Enhanced assets\", value: \"342\" },",
    "  { label: \"Policy checks\", value: \"98%\" },",
    "];",
    "",
    "export default function DashboardPage() {",
    "  return (",
    "    <main className=\"page-shell compact\">",
    "      <Link href=\"/\" className=\"back-link\">← Back to home</Link>",
    "      <p className=\"eyebrow\">Operations Dashboard</p>",
    "      <h1>Creative intelligence overview</h1>",
    "      <div className=\"metric-grid\">",
    "        {metrics.map((metric) => (",
    "          <div className=\"metric-card\" key={metric.label}>",
    "            <span>{metric.label}</span>",
    "            <strong>{metric.value}</strong>",
    "          </div>",
    "        ))}",
    "      </div>",
    "    </main>",
    "  );",
    "}",
]

FILES["app/ai-lab/page.js"] = [
    "import Link from \"next/link\";",
    "",
    "const labs = [",
    "  \"Text to speech campaign voiceovers\",",
    "  \"Speech to text transcript intelligence\",",
    "  \"Video denoising and sharpening\",",
    "  \"4K enhancement and image restoration\",",
    "  \"Brand safe generative creative briefs\",",
    "];",
    "",
    "export default function AiLabPage() {",
    "  return (",
    "    <main className=\"page-shell compact\">",
    "      <Link href=\"/\" className=\"back-link\">← Back to home</Link>",
    "      <p className=\"eyebrow\">AI Lab</p>",
    "      <h1>Media intelligence experiments</h1>",
    "      <div className=\"card-grid\">",
    "        {labs.map((lab) => (",
    "          <article className=\"feature-card\" key={lab}>",
    "            <span className=\"card-icon\">✦</span>",
    "            <h3>{lab}</h3>",
    "            <p>Part 1 placeholder prepared for real model integration in later development parts.</p>",
    "          </article>",
    "        ))}",
    "      </div>",
    "    </main>",
    "  );",
    "}",
]

FILES["app/api-lab/page.js"] = [
    "import Link from \"next/link\";",
    "",
    "export default function ApiLabPage() {",
    "  return (",
    "    <main className=\"page-shell compact\">",
    "      <Link href=\"/\" className=\"back-link\">← Back to home</Link>",
    "      <p className=\"eyebrow\">API Lab</p>",
    "      <h1>Backend route surface</h1>",
    "      <div className=\"endpoint-list\">",
    "        <div>",
    "          <strong>GET /api/health</strong>",
    "          <span>Checks whether the WebCut.ai foundation is running.</span>",
    "        </div>",
    "        <div>",
    "          <strong>POST /api/ai/creative-brief</strong>",
    "          <span>Returns a deterministic mock creative brief for later AI replacement.</span>",
    "        </div>",
    "        <div>",
    "          <strong>GET /api/agents</strong>",
    "          <span>Returns the planned creative agent map.</span>",
    "        </div>",
    "      </div>",
    "    </main>",
    "  );",
    "}",
]

FILES["app/mcp/page.js"] = [
    "import Link from \"next/link\";",
    "",
    "const tools = [",
    "  \"asset.search\",",
    "  \"media.enhance\",",
    "  \"brief.generate\",",
    "  \"approval.request\",",
    "  \"audit.write\",",
    "];",
    "",
    "export default function McpPage() {",
    "  return (",
    "    <main className=\"page-shell compact\">",
    "      <Link href=\"/\" className=\"back-link\">← Back to home</Link>",
    "      <p className=\"eyebrow\">MCP Ready Surface</p>",
    "      <h1>Future tool registry</h1>",
    "      <div className=\"endpoint-list\">",
    "        {tools.map((tool) => (",
    "          <div key={tool}>",
    "            <strong>{tool}</strong>",
    "            <span>Placeholder for safe agent tool execution.</span>",
    "          </div>",
    "        ))}",
    "      </div>",
    "    </main>",
    "  );",
    "}",
]

FILES["app/api/health/route.js"] = [
    "export async function GET() {",
    "  return Response.json({",
    "    status: \"ok\",",
    "    platform: \"WebCut.ai CreativeOps Agent Platform\",",
    "    phase: \"part-1-foundation\",",
    "    timestamp: new Date().toISOString(),",
    "    modules: [",
    "      \"studio\",",
    "      \"dashboard\",",
    "      \"ai-lab\",",
    "      \"api-lab\",",
    "      \"mcp-surface\"",
    "    ]",
    "  });",
    "}",
]

FILES["app/api/agents/route.js"] = [
    "import { agentStack } from \"@/lib/platformData\";",
    "",
    "export async function GET() {",
    "  return Response.json({",
    "    platform: \"WebCut.ai\",",
    "    agents: agentStack,",
    "    note: \"Part 1 exposes the agent map only. Real orchestration arrives in later parts.\"",
    "  });",
    "}",
]

FILES["app/api/ai/creative-brief/route.js"] = [
    "export async function POST(request) {",
    "  let payload = {};",
    "",
    "  try {",
    "    payload = await request.json();",
    "  } catch (error) {",
    "    return Response.json({ error: \"Invalid JSON body\" }, { status: 400 });",
    "  }",
    "",
    "  const brand = payload.brand || \"WebCut.ai\";",
    "  const goal = payload.goal || \"Launch a creative campaign\";",
    "  const audience = payload.audience || \"digital creators and marketing teams\";",
    "",
    "  return Response.json({",
    "    brand,",
    "    goal,",
    "    audience,",
    "    status: \"mock-generated\",",
    "    creativeBrief: {",
    "      headline: `${brand} turns raw media into campaign ready creative intelligence`,",
    "      concept: `Create a premium futuristic campaign for ${audience} focused on ${goal}.`,",
    "      channels: [\"website hero\", \"social video\", \"short form ad\", \"email banner\"],",
    "      aiWorkflows: [",
    "        \"brand safe prompt generation\",",
    "        \"speech to text asset understanding\",",
    "        \"video denoising and sharpening\",",
    "        \"human approval before publish\"",
    "      ],",
    "      governance: \"Human approval required before export or publication.\"",
    "    }",
    "  });",
    "}",
]

FILES["lib/platformData.js"] = [
    "export const platformModules = [",
    "  {",
    "    icon: \"✦\",",
    "    title: \"Creative Studio\",",
    "    description: \"A browser based workspace for campaign visuals, templates, brand kits and generated assets.\"",
    "  },",
    "  {",
    "    icon: \"◈\",",
    "    title: \"Media Intelligence\",",
    "    description: \"Prepared for text to speech, speech to text, video denoising, sharpening, 4K enhancement and image enhancement.\"",
    "  },",
    "  {",
    "    icon: \"◎\",",
    "    title: \"Agent Automation\",",
    "    description: \"A future multi agent layer for briefs, asset analysis, approvals, exports and audit trails.\"",
    "  },",
    "  {",
    "    icon: \"⌬\",",
    "    title: \"Governance Layer\",",
    "    description: \"Human approval, content safety, policy checks, observability and controlled tool execution.\"",
    "  }",
    "];",
    "",
    "export const agentStack = [",
    "  { name: \"Creative Director Agent\", role: \"Turns business goals into campaign briefs.\" },",
    "  { name: \"Media Intelligence Agent\", role: \"Analyses audio, image and video assets.\" },",
    "  { name: \"Enhancement Agent\", role: \"Plans denoising, sharpening, upscale and restoration jobs.\" },",
    "  { name: \"Governance Agent\", role: \"Checks brand, policy, safety and approval requirements.\" },",
    "  { name: \"Export Agent\", role: \"Prepares channel specific creative outputs.\" }",
    "];",
    "",
    "export const launchSteps = [",
    "  {",
    "    phase: \"01\",",
    "    title: \"Foundation\",",
    "    detail: \"Next.js structure, futuristic UI, health route and mock creative brief route.\"",
    "  },",
    "  {",
    "    phase: \"02\",",
    "    title: \"Workspace\",",
    "    detail: \"Canvas editor, uploads, asset library, templates and brand kit controls.\"",
    "  },",
    "  {",
    "    phase: \"03\",",
    "    title: \"AI Services\",",
    "    detail: \"Text, audio, image and video intelligence with secure service adapters.\"",
    "  },",
    "  {",
    "    phase: \"04\",",
    "    title: \"Agents\",",
    "    detail: \"Multi agent orchestration, Model Context Protocol tools, approvals and audit logs.\"",
    "  },",
    "  {",
    "    phase: \"05\",",
    "    title: \"Cloud Production\",",
    "    detail: \"AWS native deployment path with storage, queues, observability and governance.\"",
    "  }",
    "];",
]

FILES["app/globals.css"] = [
    ":root {",
    "  --background: #050614;",
    "  --panel: rgba(15, 20, 45, 0.78);",
    "  --panel-strong: rgba(18, 26, 58, 0.92);",
    "  --text: #f6f7ff;",
    "  --muted: #b9c3e6;",
    "  --line: rgba(150, 170, 255, 0.2);",
    "  --cyan: #72f7ff;",
    "  --violet: #a97cff;",
    "  --pink: #ff6ec7;",
    "  --green: #7dffbd;",
    "}",
    "",
    "* {",
    "  box-sizing: border-box;",
    "}",
    "",
    "body {",
    "  margin: 0;",
    "  background:",
    "    radial-gradient(circle at 15% 10%, rgba(114, 247, 255, 0.18), transparent 30%),",
    "    radial-gradient(circle at 80% 0%, rgba(169, 124, 255, 0.22), transparent 28%),",
    "    radial-gradient(circle at 50% 90%, rgba(255, 110, 199, 0.14), transparent 32%),",
    "    var(--background);",
    "  color: var(--text);",
    "  font-family: Arial, Helvetica, sans-serif;",
    "}",
    "",
    "a {",
    "  color: inherit;",
    "  text-decoration: none;",
    "}",
    "",
    ".page-shell {",
    "  width: min(1180px, calc(100% - 40px));",
    "  margin: 0 auto;",
    "  padding: 56px 0;",
    "}",
    "",
    ".compact {",
    "  min-height: 100vh;",
    "}",
    "",
    ".hero-grid {",
    "  display: grid;",
    "  grid-template-columns: minmax(0, 1.05fr) minmax(320px, 0.95fr);",
    "  gap: 32px;",
    "  align-items: center;",
    "  min-height: 76vh;",
    "}",
    "",
    ".hero-copy h1, .compact h1 {",
    "  margin: 0;",
    "  font-size: clamp(44px, 8vw, 92px);",
    "  line-height: 0.92;",
    "  letter-spacing: -0.08em;",
    "}",
    "",
    ".hero-text {",
    "  max-width: 680px;",
    "  color: var(--muted);",
    "  font-size: 20px;",
    "  line-height: 1.65;",
    "}",
    "",
    ".eyebrow {",
    "  color: var(--cyan);",
    "  font-size: 13px;",
    "  font-weight: 700;",
    "  letter-spacing: 0.18em;",
    "  text-transform: uppercase;",
    "}",
    "",
    ".button-row {",
    "  display: flex;",
    "  flex-wrap: wrap;",
    "  gap: 14px;",
    "  margin-top: 28px;",
    "}",
    "",
    ".primary-button, .secondary-button {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  min-height: 48px;",
    "  padding: 0 22px;",
    "  border-radius: 999px;",
    "  border: 1px solid var(--line);",
    "  font-weight: 800;",
    "}",
    "",
    ".primary-button {",
    "  background: linear-gradient(135deg, var(--cyan), var(--violet), var(--pink));",
    "  color: #04101c;",
    "  box-shadow: 0 22px 80px rgba(114, 247, 255, 0.18);",
    "}",
    "",
    ".secondary-button {",
    "  background: rgba(255, 255, 255, 0.06);",
    "  color: var(--text);",
    "}",
    "",
    ".button-reset {",
    "  border: 0;",
    "  cursor: pointer;",
    "}",
    "",
    ".hero-panel {",
    "  position: relative;",
    "  min-height: 520px;",
    "  border: 1px solid var(--line);",
    "  border-radius: 36px;",
    "  background: linear-gradient(145deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.03));",
    "  overflow: hidden;",
    "  box-shadow: 0 30px 100px rgba(0, 0, 0, 0.35);",
    "}",
    "",
    ".hero-panel::before {",
    "  content: \"\";",
    "  position: absolute;",
    "  inset: 22px;",
    "  border: 1px solid rgba(255, 255, 255, 0.16);",
    "  border-radius: 28px;",
    "  background-image:",
    "    linear-gradient(rgba(114, 247, 255, 0.08) 1px, transparent 1px),",
    "    linear-gradient(90deg, rgba(114, 247, 255, 0.08) 1px, transparent 1px);",
    "  background-size: 34px 34px;",
    "}",
    "",
    ".orb {",
    "  position: absolute;",
    "  width: 230px;",
    "  height: 230px;",
    "  border-radius: 999px;",
    "  filter: blur(4px);",
    "}",
    "",
    ".orb-one {",
    "  top: 55px;",
    "  right: 60px;",
    "  background: radial-gradient(circle, rgba(114, 247, 255, 0.85), transparent 62%);",
    "}",
    "",
    ".orb-two {",
    "  bottom: 30px;",
    "  left: 42px;",
    "  background: radial-gradient(circle, rgba(255, 110, 199, 0.72), transparent 62%);",
    "}",
    "",
    ".glass-card {",
    "  position: absolute;",
    "  left: 42px;",
    "  right: 42px;",
    "  bottom: 46px;",
    "  padding: 26px;",
    "  border: 1px solid rgba(255, 255, 255, 0.18);",
    "  border-radius: 28px;",
    "  background: rgba(4, 8, 24, 0.74);",
    "  backdrop-filter: blur(24px);",
    "}",
    "",
    ".glass-card span, .metric-card span, .endpoint-list span, .stack-item span {",
    "  color: var(--muted);",
    "}",
    "",
    ".glass-card strong {",
    "  display: block;",
    "  margin: 10px 0;",
    "  font-size: 26px;",
    "}",
    "",
    ".section, .split-section {",
    "  margin-top: 70px;",
    "}",
    "",
    ".section-heading {",
    "  max-width: 760px;",
    "}",
    "",
    ".section-heading h2, .split-section h2 {",
    "  margin: 0;",
    "  font-size: clamp(32px, 5vw, 56px);",
    "  letter-spacing: -0.05em;",
    "}",
    "",
    ".card-grid, .metric-grid {",
    "  display: grid;",
    "  grid-template-columns: repeat(4, minmax(0, 1fr));",
    "  gap: 18px;",
    "  margin-top: 28px;",
    "}",
    "",
    ".feature-card, .metric-card, .workspace-sidebar, .canvas-shell, .endpoint-list div, .stack-item, .timeline-item {",
    "  border: 1px solid var(--line);",
    "  border-radius: 26px;",
    "  background: var(--panel);",
    "  box-shadow: 0 22px 70px rgba(0, 0, 0, 0.25);",
    "}",
    "",
    ".feature-card {",
    "  padding: 24px;",
    "}",
    "",
    ".card-icon {",
    "  display: inline-flex;",
    "  width: 42px;",
    "  height: 42px;",
    "  align-items: center;",
    "  justify-content: center;",
    "  border-radius: 14px;",
    "  background: rgba(114, 247, 255, 0.12);",
    "  color: var(--cyan);",
    "}",
    "",
    ".feature-card p, .muted, .timeline-item p {",
    "  color: var(--muted);",
    "  line-height: 1.65;",
    "}",
    "",
    ".split-section {",
    "  display: grid;",
    "  grid-template-columns: 0.9fr 1.1fr;",
    "  gap: 28px;",
    "  align-items: start;",
    "}",
    "",
    ".stack-list, .endpoint-list {",
    "  display: grid;",
    "  gap: 14px;",
    "}",
    "",
    ".stack-item, .endpoint-list div {",
    "  display: flex;",
    "  justify-content: space-between;",
    "  gap: 18px;",
    "  padding: 18px;",
    "}",
    "",
    ".timeline {",
    "  display: grid;",
    "  gap: 14px;",
    "  margin-top: 28px;",
    "}",
    "",
    ".timeline-item {",
    "  display: grid;",
    "  grid-template-columns: 80px 1fr;",
    "  gap: 18px;",
    "  padding: 20px;",
    "}",
    "",
    ".timeline-item > span {",
    "  display: inline-flex;",
    "  width: 54px;",
    "  height: 54px;",
    "  align-items: center;",
    "  justify-content: center;",
    "  border-radius: 18px;",
    "  background: linear-gradient(135deg, rgba(114, 247, 255, 0.25), rgba(169, 124, 255, 0.2));",
    "  color: var(--cyan);",
    "  font-weight: 900;",
    "}",
    "",
    ".back-link {",
    "  display: inline-flex;",
    "  margin-bottom: 28px;",
    "  color: var(--cyan);",
    "  font-weight: 800;",
    "}",
    "",
    ".workspace {",
    "  display: grid;",
    "  grid-template-columns: 360px 1fr;",
    "  gap: 22px;",
    "  align-items: stretch;",
    "}",
    "",
    ".workspace-sidebar, .canvas-shell {",
    "  padding: 26px;",
    "}",
    "",
    ".canvas-shell {",
    "  min-height: 620px;",
    "  display: grid;",
    "  place-items: center;",
    "}",
    "",
    ".canvas-frame {",
    "  width: min(520px, 100%);",
    "  aspect-ratio: 1;",
    "  display: grid;",
    "  place-items: center;",
    "  text-align: center;",
    "  padding: 28px;",
    "  border-radius: 34px;",
    "  border: 1px solid rgba(255, 255, 255, 0.2);",
    "  background:",
    "    linear-gradient(135deg, rgba(114, 247, 255, 0.22), rgba(169, 124, 255, 0.18), rgba(255, 110, 199, 0.16)),",
    "    rgba(255, 255, 255, 0.05);",
    "}",
    "",
    ".metric-grid {",
    "  grid-template-columns: repeat(4, minmax(0, 1fr));",
    "}",
    "",
    ".metric-card {",
    "  padding: 24px;",
    "}",
    "",
    ".metric-card strong {",
    "  display: block;",
    "  margin-top: 14px;",
    "  font-size: 42px;",
    "}",
    "",
    "@media (max-width: 900px) {",
    "  .hero-grid, .split-section, .workspace {",
    "    grid-template-columns: 1fr;",
    "  }",
    "",
    "  .card-grid, .metric-grid {",
    "    grid-template-columns: repeat(2, minmax(0, 1fr));",
    "  }",
    "}",
    "",
    "@media (max-width: 560px) {",
    "  .page-shell {",
    "    width: min(100% - 24px, 1180px);",
    "    padding: 30px 0;",
    "  }",
    "",
    "  .card-grid, .metric-grid {",
    "    grid-template-columns: 1fr;",
    "  }",
    "",
    "  .stack-item, .endpoint-list div {",
    "    flex-direction: column;",
    "  }",
    "}",
]

def backup_existing_file(target):
    if target.exists():
        backup_target = BACKUP_DIR / target.relative_to(ROOT)
        backup_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(target, backup_target)


def write_file(relative_path, lines):
    target = ROOT / relative_path
    backup_existing_file(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    for relative_path, lines in FILES.items():
        write_file(relative_path, lines)

    print("WebCut.ai Part 1 foundation created successfully.")
    if BACKUP_DIR.exists():
        print(f"Existing overwritten files were backed up at: {BACKUP_DIR}")
    print("Next commands:")
    print("npm install")
    print("npm run dev")
    print("Open http://localhost:3000")


if __name__ == "__main__":
    main()
